services:
  app:
    build: .
    command: sh -c "alembic upgrade head"
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U avg_user -d avg_messenger"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
