"""added chats and chat_members tables

Revision ID: 26d6afd6d79e
Revises: None
Create Date: 2026-03-15 03:11:19.988408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d6afd6d79e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("INSERT INTO chats (id, name) VALUES (1, 'Origin')")

    op.create_table('chat_members',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )

    op.execute("INSERT INTO chat_members (chat_id, user_id) SELECT 1, id FROM users")

    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=True))

    op.execute("UPDATE messages SET chat_id = 1")

    op.alter_column('messages', 'chat_id', nullable=False)

    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    op.drop_table('chat_members')
    op.drop_table('chats')
    # ### end Alembic commands ###
